### ISSUE TITLE
电池除了拆成八位还需要做什么吗？

### ISSUE THREAD

**Issue by jardenliu** [ChalesYu/S400CA-Hackintosh#1]
我的F450VC  拆了八位可以显示电池和电量，但是电量不会更新。举个例子就是我一开机显示95%   用了一段时间之后还是显示95  需要手动点一下才会更新百分比

**Comment by ChalesYu** [comment]
可能是 ACPIBatteryManager的问题，你可以试试打开它的Info.plist ,找到 IOKitPersonalities -> ACPI Battery Manager -> Configuration 把里面的 FirstPollDelay 改成 1600

**Comment by jardenliu** [comment]
找到原因了，是APFS和TRIM patch 导致的

**Comment by ChalesYu** [comment]
找到原因了就好，是需要移除TRIM patch吗？

**Comment by jardenliu** [comment]
对，不开启trim就好了~
这里也说到了，https://github.com/RehabMan/OS-X-ACPI-Battery-Driver/issues/21
